version: '3'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/cbomb
  unit:
    image: ruby:2.3
    volumes:
      - ${WORKSPACE_PATH}/${JOB_NAME}:/app
    working_dir: /app
    command: bash -c "bundle install && bundle exec ruby app_test.rb"
  production:
    image: ${DOCKER_USER_ID}/cbomb:${BUILD_NUMBER}
    ports:
      - 8000:8000