version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /myproject/start
    volumes:
      - .:/code
      - ./staticfiles:/staticfiles
    expose:
      - '8000'