version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - ./staticfiles:/staticfiles
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application